--------------------------------------------------------------------------------------------------
--------------------------------------TALLER 2----------------------------------------------------

---PUNTO 1

CREATE OR REPLACE VIEW AS MEDIOS_PAGO_CLIENTES AS
    SELECT CLI.ID, CLI.NOMBRES || ' ' || CLI.APELLIDOS AS NOMBRE_CLIENTE, PAG.ID AS MEDIO_PAGO_ID, PAG.TIPO, PAG.DESCRIPCION AS DETALLE_MEDIO_PAGO
    FROM CLIENTES CLI INNER JOIN MEDIOS_PAGO PAG ON PAG.CLIENTE_ID = CLI.ID
    
---PUNTO 2

CREATE OR REPLACE VIEW VIAJES_CLIENTES AS
    SELECT SER.FECHA AS FECHA_VIAJE, COND.NOMBRES || ' ' || COND.APELIDOS AS NOMBRE_CONDUCTOR, VEHI.PLACA AS PLACA_VEHICULO, 
            CLI.NOMBRES || ' ' || CLI.APELLIDOS AS NOMBRE_CLIENTE, SUM(DETFAC.VALOR + FAC.VALOR) AS VALOR_TOTAL, SER.TARIFA_DINAMICA, 
            VEHI.TIPO_SERVICIO, CIU.NOMBRE AS CIUDAD_VIAJE
    FROM SERVICIOS SER INNER JOIN CONDUCTORES_VEHICULOS CONVEHI ON SER.CONDUCTORES_VEHICULOS_ID = CONVEHI.ID
                       INNER JOIN CONDUCTORES COND ON CONVEHI.CONDUCTOR_ID = COND.ID
                       INNER JOIN VEHICULOS VEHI ON CONVEHI.VEHICULO_ID = VEHI.ID
                       INNER JOIN CLIENTES CLI ON SER.CLIENTE_ID = CLI.ID
                       INNER JOIN FACTURAS FAC ON FAC.SERVICIO_ID = SER.ID
                       INNER JOIN DETALLES_FACTURAS DETFAC ON DETFAC.FACTURA_ID = FAC.ID
                       INNER JOIN CIUDADES CIU ON CLI.CIUDAD_ID = CIU.ID
    GROUP BY SER.FECHA, COND.NOMBRES, COND.APELIDOS, VEHI.PLACA, CLI.NOMBRES, CLI.APELLIDOS, SER.TARIFA_DINAMICA, VEHI.TIPO_SERVICIO, CIU.NOMBRE;
    
---PUNTO 3

EXPLAIN PLAN SET STATEMENT_ID = 'EP_VIAJES_CLIENTES' FOR
  SELECT * FROM VIAJES_CLIENTES;
  
SELECT * FROM TABLE
  (DBMS_XPLAN.DISPLAY('PLAN_TABLE','EP_VIAJES_CLIENTES','TYPICAL'))
  
  CREATE UNIQUE INDEX CIUDAD ON CIUDADES(NOMBRE); -- Se crea un indice parala tabla ciudades para dar optimizacion a la busqueda

---PUNTO 4
---VER TABLA CIUDADES DONDE SE EVIDENCIA LA CREACION DE LOS 3 NUEVOS CAMPOS CON SUS RESPECTIVOS VALORES.
SELECT * FROM CIUDADES;