
-- Punto 2
     -- 2a
     CREATE TABLESPACE uber DATAFILE 'uber.dbf' SIZE 2G ONLINE;

    -- 2b
    CREATE UNDO TABLESPACE undouber
        DATAFILE 'undouber_1a.dbf'
        SIZE 25M AUTOEXTEND ON
        RETENTION GUARANTEE;
    
    --2c
        CREATE BIGFILE TABLESPACE bigfileuber
        DATAFILE 'bigfileuber_1a.dbf'
        SIZE 5G;
        
    --2d

    ALTER SYSTEM SET UNDO_TABLESPACE = undouber;
    



-- Punto 3
CREATE USER usrUber
IDENTIFIED BY usrUber
DEFAULT TABLESPACE uber
QUOTA UNLIMITED ON uber;


GRANT CREATE SESSION, DBA TO usrUber

-- Punto 4

CREATE PROFILE CLERK LIMIT 
  PASSWORD_LIFE_TIME               40   -- dias
  SESSIONS_PER_USER                 1   -- Una por usuario
  IDLE_TIME                        10   -- minutos
  FAILED_LOGIN_ATTEMPTS             4;  -- Logins fallidos

CREATE PROFILE DEVELOPMENT LIMIT 
  PASSWORD_LIFE_TIME              100   -- dias
  SESSIONS_PER_USER                 2   -- Dos por usuario
  IDLE_TIME                        30   -- minutos
  FAILED_LOGIN_ATTEMPTS     UNLIMITED;  -- Logins ilimitados


-- Punto 5

    --5a
    CREATE USER user1
    IDENTIFIED BY user1
    DEFAULT TABLESPACE uber;
    GRANT CREATE SESSION TO user1;
    ALTER USER user1 PROFILE CLERK;
    
    CREATE USER user2
    IDENTIFIED BY user2
    DEFAULT TABLESPACE uber;
    GRANT CREATE SESSION TO user2;
    ALTER USER user2 PROFILE CLERK;
    
    CREATE USER user3
    IDENTIFIED BY user3
    DEFAULT TABLESPACE uber;
    GRANT CREATE SESSION TO user3;
    ALTER USER user3 PROFILE DEVELOPMENT;
    
    CREATE USER user4
    IDENTIFIED BY user4
    DEFAULT TABLESPACE uber;
    GRANT CREATE SESSION TO user4;
    ALTER USER user4 PROFILE DEVELOPMENT;

    --5b
    ALTER USER user2 ACCOUNT LOCK;

   --6 CREACION DE TABLAS
    
    CREATE TABLE CLIENTES
    (
        ID INTEGER PRIMARY KEY NOT NULL,
        NOMBRES VARCHAR2(255) NULL,
        APELLIDOS VARCHAR2(255) NULL,
        FOTO VARCHAR2(255),
        CORREO VARCHAR2(255) NULL,
        CELULAR VARCHAR2(255) NULL,
        USUARIO VARCHAR2(255) NULL,
        CONTRASEÑA VARCHAR2(255) NULL,
        CODIGO_INVITADO VARCHAR2(255) NULL,
        IDIOMA_ID INTEGER NOT NULL,
        CIUDAD_ID INTEGER NOT NULL
    );
    
    CREATE TABLE MEDIOS_PAGO
    (
        ID INTEGER PRIMARY KEY NOT NULL,
        DESCRIPCION VARCHAR2(255) NULL
    );
    
    CREATE TABLE SERVICIOS
    (
        ID INTEGER PRIMARY KEY NOT NULL,
        FECHA DATE NOT NULL,
        HORA TIMESTAMP NOT NULL,
        DISTANCIA DECIMAL (*,2) NULL,
        TIEMPO_REQUERIDO INTEGER NULL,
        DIRECCION_ORIGEN VARCHAR2(255) NULL,
        DIRECCION_DESTINO VARCHAR2(255) NULL,
        TARIFA DECIMAL (*,2) NULL,
        ESTADO VARCHAR2 (255) NULL,
        TARIFA_DINAMICA VARCHAR2(1) CHECK ((TARIFA_DINAMICA = 'V') OR (TARIFA_DINAMICA = 'F')),
        MEDIO_PAGO_ID INTEGER NOT NULL,
        CONDUCTOR_ID INTEGER NOT NULL,
        VEHICULO_ID INTEGER NOT NULL,
        CLIENTE_ID INTEGER NOT NULL,
        SERVICIO_COMPARTIDO_CLIENTE_ID INTEGER NULL
    );
    
    CREATE TABLE VEHICULOS
    (
        ID INTEGER PRIMARY KEY NOT NULL,
        PLACA VARCHAR2(255) NULL,
        MARCA VARCHAR2(255) NULL,
        LINEA VARCHAR2(255) NULL,
        MODELO VARCHAR2(255) NULL,
        TIPO_SERVICIO VARCHAR2(255) CHECK(TIPO_SERVICIO IN ('UberX','Uber Black'))
    );
    
    CREATE TABLE CONDUCTORES_VEHICULOS
    (
        ID INTEGER PRIMARY KEY NOT NULL,
        CONDUCTOR_ID INTEGER NOT NULL,
        VEHICULO_ID INTEGER NOT NULL
    );
    
    CREATE TABLE DETALLES_UBICACION_SERVICIOS
    (
        ID INTEGER PRIMARY KEY NOT NULL,
        LATITUD VARCHAR2(255) NULL,
        LONGITUD VARCHAR2(255) NULL,
        SERVICIO_ID INTEGER NOT NULL
    );
    
    CREATE TABLE CLIENTES_EMPRESAS
    (
        ID INTEGER PRIMARY KEY NOT NULL,
        CLIENTE_ID INTEGER NOT NULL,
        EMPRESA_ID INTEGER NOT NULL
    );
    
    CREATE TABLE FACTURAS
    (
        ID INTEGER PRIMARY KEY NOT NULL,
        FECHA DATE,
        NUMERO INTEGER,
        SERVICIO_ID INTEGER NOT NULL
    );
    
    
CREATE TABLE IDIOMAS 
 (
    ID INTEGER PRIMARY KEY NOT NULL,
    DESCRIPCION VARCHAR2(255) NULL,
    ABREVIATURA VARCHAR2(255) NULL
 );


CREATE TABLE PAISES 
 (
    ID INTEGER PRIMARY KEY NOT NULL,
    NOMBRE VARCHAR2(255) NULL,
    MONEDA VARCHAR2(255)NULL,
    INDICATIVO VARCHAR2(255) NULL
 );
 
 CREATE TABLE CIUDADES
 (
    ID INTEGER PRIMARY KEY NOT NULL,
    NOMBRE VARCHAR2(255) NULL,
    CODIGO_POSTAL VARCHAR2(255) NULL,
    PAIS_ID INTEGER NOT NULL
 );
 
 CREATE TABLE CLIENTES_MEDIOS_PAGO 
 (
    ID INTEGER PRIMARY KEY NOT NULL,
    CLIENTE_ID INTEGER NOT NULL,
    MEDIO_PAGO_ID INTEGER NOT NULL,
    ENVIAR_CORREO VARCHAR2(1) CHECK ((ENVIAR_CORREO = 'V') OR (ENVIAR_CORREO = 'F')) NULL 
 );
 
 CREATE TABLE CODIGOS_PROMOCIONALES 
 (
    ID INTEGER PRIMARY KEY NOT NULL,
    CODIGO VARCHAR2(255) NULL,
    CLIENTE_ID INTEGER NOT NULL
);

CREATE TABLE CONDUCTORES 
 (
    ID INTEGER PRIMARY KEY NOT NULL,
    CEDULA VARCHAR2(255) NULL,
    NOMBRES VARCHAR2(255) NULL,
    APELIDOS VARCHAR2(255) NULL,
    FOTO VARCHAR2(255) NULL,
    CORREO VARCHAR2(255) NULL,
    CELULAR VARCHAR2(255) NULL,
    NUMERO_CUENTA VARCHAR2(255) NOT NULL,
    ENTIDAD_BANCARIA VARCHAR2(255)NOT NULL,
    IDIOMA_ID INTEGER NOT NULL,
    CIUDAD_ID INTEGER NOT NULL
);
 
 CREATE TABLE EMPRESAS 
 (
    ID INTEGER PRIMARY KEY NOT NULL,
    NIT VARCHAR2(255) NULL,
    NOMBRE VARCHAR2(255) NULL,
    DIRECCION VARCHAR2(255) NULL,
    TELEFONO VARCHAR2(255) NULL,
    CORREO VARCHAR2(255) NULL
);

 CREATE TABLE EMPRESAS_MEDIOS_PAGO 
 (
    ID INTEGER PRIMARY KEY NOT NULL,
    EMPRESA_ID INTEGER NOT NULL,
    MEDIO_PAGO_ID INTEGER NOT NULL
);

CREATE TABLE DETALLES_FACTURAS 
 (
    ID INTEGER PRIMARY KEY NOT NULL,
    IVA DECIMAL (*,2),
    COMISION_UBER DECIMAL (*,2) DEFAULT 0.34,
    PROPINAS DECIMAL (*,2),
    HONORARIOS DECIMAL (*,2),
    REGARGOS DECIMAL (*,2),
    PEAJES DECIMAL (*,2),
    SUB_TOTAL DECIMAL (*,2),
    TOTAL DECIMAL (*,2),
    FACTURA_ID INTEGER NOT NULL
);

CREATE TABLE DETALLES_MEDIOS_PAGO
(
    ID INTEGER PRIMARY KEY NOT NULL,
    FRANQUICIA VARCHAR2(255) NULL,
    FECHA_EXPIRACION VARCHAR2(255) NULL,
    NUMERO_TARJETA VARCHAR2(255) NULL,
    CODIGO_CVV VARCHAR2(255) NULL,
    ENTIDAD_BANCARIA VARCHAR2(255) NULL,
    MEDIO_PAGO_ID INTEGER NOT NULL
);
    
--SE CREA LA SCUENCIA PARA DAR CONTROL A LA NUMERACION DE LA FACTURACION
    CREATE SEQUENCE AGENCIES_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCYCLE;
    
--CARDINALIDAD
    --TABLA CLIENTES
    ALTER TABLE CLIENTES
        ADD CONSTRAINT FK_CLIENTE_IDIOMA FOREIGN KEY (IDIOMA_ID) REFERENCES IDIOMAS (ID);
    ALTER TABLE CLIENTES
        ADD CONSTRAINT FK_CLIENTE_CIUDAD FOREIGN KEY (CIUDAD_ID) REFERENCES CIUDADES (ID);
        
    --TABLA SERVICIOS
    ALTER TABLE SERVICIOS
        ADD CONSTRAINT FK_SERVICIO_MEDIO_PAGO FOREIGN KEY (MEDIO_PAGO_ID) REFERENCES MEDIOS_PAGO (ID);
    ALTER TABLE SERVICIOS    
        ADD CONSTRAINT FK_SERVICIO_CONDUCTOR FOREIGN KEY (CONDUCTOR_ID) REFERENCES CONDUCTORES (ID);
    ALTER TABLE SERVICIOS    
        ADD CONSTRAINT FK_SERVICIO_VEHICULO FOREIGN KEY (VEHICULO_ID) REFERENCES VEHICULOS (ID);
    ALTER TABLE SERVICIOS     
        ADD CONSTRAINT FK_SERVICIO_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES (ID);
    ALTER TABLE SERVICIOS     
        ADD CONSTRAINT FK_SERVICIO_COMPARTIDO_CLIENTE FOREIGN KEY (SERVICIO_COMPARTIDO_CLIENTE_ID) REFERENCES CLIENTES (ID);
        
    --TABLA CONDUCTORES_VEHICULOS
    ALTER TABLE CONDUCTORES_VEHICULOS
        ADD CONSTRAINT FK_CONDUCTOR_VEHICULO_CONDUCTO FOREIGN KEY (CONDUCTOR_ID) REFERENCES CONDUCTORES (ID);
    ALTER TABLE CONDUCTORES_VEHICULOS
        ADD CONSTRAINT FK_CONDUCTOR_VEHICULO_VEHICULO FOREIGN KEY (VEHICULO_ID) REFERENCES VEHICULOS (ID);
        
    --TABLA DETALLES_UBICACION_SERVICIOS
     ALTER TABLE DETALLES_UBICACION_SERVICIOS
        ADD CONSTRAINT FK_DETALLES_UBICACION_SERVICIO FOREIGN KEY (SERVICIO_ID) REFERENCES SERVICIOS (ID);
        
    --TABLA CLIENTES_EMPRESAS
    ALTER TABLE CLIENTES_EMPRESAS
        ADD CONSTRAINT FK_CLIENTES_EMPRESAS_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES (ID);
     ALTER TABLE CLIENTES_EMPRESAS    
        ADD CONSTRAINT FK_CLIENTES_EMPRESASA_EMPESA FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESAS (ID);
        
     --TABLA FACTURAS
     ALTER TABLE FACTURAS
        ADD CONSTRAINT FK_FACTURAS_SERVICIO FOREIGN KEY (SERVICIO_ID) REFERENCES SERVICIOS (ID);   
        
    -- TABLA CIUDADES
    ALTER TABLE CIUDADES
        ADD CONSTRAINT FK_CIUDAD_PAIS FOREIGN KEY (PAIS_ID) REFERENCES PAISES (ID);    
        
    --TABLA CLIENTES_MEDIOS_PAGO 
    ALTER TABLE CLIENTES_MEDIOS_PAGO
        ADD CONSTRAINT FK_CLIENTE_MEDIO_PAGO_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES (ID);
    ALTER TABLE CLIENTES_MEDIOS_PAGO    
        ADD CONSTRAINT FK_CLIENTE_MEDIO_PAGO FOREIGN KEY (MEDIO_PAGO_ID) REFERENCES MEDIOS_PAGO (ID);
        
    --TABLA CODIGOS_PROMOCIONALES 
    ALTER TABLE CODIGOS_PROMOCIONALES
        ADD CONSTRAINT FK_COD_PROMOCIONALES_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES (ID); 
        
    --TABLA CONDUCTORES
    ALTER TABLE CONDUCTORES
        ADD CONSTRAINT FK_CONDUCTOR_IDIOMA FOREIGN KEY (IDIOMA_ID) REFERENCES IDIOMAS (ID); 
    ALTER TABLE CONDUCTORES
        ADD CONSTRAINT FK_CONDUCTORES_CIUDAD FOREIGN KEY (CIUDAD_ID) REFERENCES CIUDADES (ID);  
        
    --TABLA EMPRESAS_MEDIOS_PAGO
    ALTER TABLE EMPRESAS_MEDIOS_PAGO
        ADD CONSTRAINT FK_MEDIOS_PAGO_EMPRESAS FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESAS (ID); 
    ALTER TABLE EMPRESAS_MEDIOS_PAGO
        ADD CONSTRAINT FK_MEDIOS_PAGO_MEDIOPAGO FOREIGN KEY (MEDIO_PAGO_ID) REFERENCES MEDIOS_PAGO (ID);  
        
    --TABLA DETALLES_MEDIOS_PAGO    
    ALTER TABLE DETALLES_MEDIOS_PAGO
        ADD CONSTRAINT FK_MEDIOS_PAGO_DETALLE FOREIGN KEY (MEDIO_PAGO_ID) REFERENCES MEDIOS_PAGO (ID); 
        
    --TABLA DETALLES_FACTURAS   
    ALTER TABLE DETALLES_FACTURAS
        ADD CONSTRAINT FK_DETALLES_FACTURA FOREIGN KEY (FACTURA_ID) REFERENCES FACTURAS (ID); 